### ISSUE TITLE
Does not interact well with existing blueprints and objects from pre-mod

### ISSUE THREAD

**Issue by ColinBundschu** [KeinNiemand/Factorio-GhostOnWater#19]
Existing blueprints cannot be made water placeable, only blueprints created since the mod was installed. The blue highlighting of entities which overlap a ghost in a "compatible" way only work with objects placed since the mod was installed.  Otherwise the collision is red, even if the objects would normally highlight blue.

**Comment by ColinBundschu** [comment]
It also sometimes turns red on its own placed ghosts (on land at least) intermittently within the same blueprint. As in, if the blueprint has two robotports, then when the blueprint is lined up sometimes one will be blue and one will be red.

**Comment by KeinNiemand** [comment]
Existing Blueprints can be made water placeable I've done it myself, are you sure you put the blueprint in your inventory? The mod can only modifiy blueprints in your inventory not blueprints that are inside your game/save file blueprint library (it has to be physically in the inventory a putting it in the hotbar will not work as that just creates a link you need the actual blueprint/book item in your inventory (with books only the selcted BP get's converted)). Anway not somthing that can be fixed as it's not possible to access BP in your BP libary.
The collision is red because the water placeable version of building is technically a different entity that automatically converts back to the original entity (ghost) as soon it's on land that's why it immediately turns after being build on land it's converted back to the original building which is a different entity then the water placeable dummy version (water ghost). This also is somthing that can't be fixed becouse the water placable version needs to be a diffrent entity so it can be placed on water.

**Comment by ColinBundschu** [comment]
I can confirm that the issue was in fact blueprints library blueprints, and the collision issue makes sense. The "old" vs. "new" blueprints was me mistaking correlation with causation.
