### ISSUE TITLE
Feature Request: Possible overlap fix implementation

### ISSUE THREAD

**Issue by ColinBundschu** [KeinNiemand/Factorio-GhostOnWater#22]
Assuming that during placement it is possible to:

1. Detect which entities in the blueprint are completely over land/landfill/space platform
2. Change the entity id of any entities being placed in real time

Then changing the entity id for any blueprint entity that is hovered completely over land to the entity id of the placed version on land should fix issues with red collision placement highlighting. It also has the additional upside of making all ghosts placed on land with a water placeable blueprint compatible with regular, non water placeable blueprints.

**Comment by KeinNiemand** [comment]
This is not possible, because there is no way to do 1. or 2.
The game does not trigger an even for placing blueprints so it's not possible to change BP entities in real time, there's no way (I know off) to detect what the entitles in the BP are hovering over. There also no build event or anything for entities that are attempted to be build without actually being build. The mod works the way it does due to API limitations.

**Comment by ColinBundschu** [comment]
Thanks for the reply. Figure I'd at least try :)
