### ISSUE TITLE
While loading mods... waterGhost-wooden-trashdump-10x10

### ISSUE THREAD

**Issue by oEjk** [KeinNiemand/Factorio-GhostOnWater#32]
Error ModManager.cpp:1560: Error while sorting items-to-place for entity prototype "waterGhost-wooden-trashdump-10x10" (container): item-to-place "waterGhost-wooden-chest" count (100) can't be larger than the the item stack size (50).

Requires mod to be disabled to load.

Please advise

**Comment by KeinNiemand** [comment]
What are the exact mods you're using? I know somone reported somthing similar with merging chests but when I tried merging chests it works for me, so can you give me your full mod list?

**Comment by oEjk** [comment]
[mod-list.txt](https://github.com/KeinNiemand/Factorio-GhostOnWater/files/10580844/mod-list.txt)
includes WideChests and WideChestsAllTypes

**Comment by KeinNiemand** [comment]
Weird when I use both of these 2 mods the game doesn't crash for me. Are all of your mods (especially Merging Chests and Merging Chests All Types) up do date? What mod settings do you have for merging chests?

 the error you are getting shows a crash because my water ghost from my mod doesn't have a large enough stack size to build a 10x10 merged chest (which takes 100 chests to build while stack size is 50), but that shoudn't happen becouse the dummy copy my mods makes are copys that include the stack size. 
The only 2 ways I can explain this are that either one of your other mods is changing stack size of my water ghost entitys retroactively, or that the version of merging chests you have for some reason updates it's stack size in data-final-fixes after it's already been copied by mod.

**Comment by oEjk** [comment]
Mods are are all up to date. I have "wooden chest" set in Merging Chests, but "Merging Chests All Types" should override that

gmos has a setting fix https://mods.factorio.com/mod/GhostOnWater/discussion/638d163e53224d794ae72c94?quote=4

"the error you are getting shows a crash because my water ghost from my mod doesn't have a large enough stack size to build a 10x10 merged chest (which takes 100 chests to build while stack size is 50)" - can it use more than one stack?

Did you try making a new game with the mods installed? this is where I saw the bug.

**Comment by oEjk** [comment]
There is a fix where you enable GoW after the game is loaded, and the error is gone on restart

**Comment by KeinNiemand** [comment]
"can it use more than one stack?" No and that's why it's crashing, and this is also why merging chests increases chest stack size. Normally this change to stack size would be copied when my mod creastes is dummy entitys but for some reason it happens after ghost on water loaded.

"Did you try making a new game with the mods installed? this is where I saw the bug."

And that's what's making this so weid it shoudn't be inconsistant like that, as long as settings and mods are the same this crash should happen 100% of the time or never, this is a data stage crash that happens while the game is loading, not a in game crash so nothing you do in game should matter or have any effect (other then startup mod settings and installed mods). Starting the game with wide chests, and then enabling ghost on water shouldn't have any different effect. Somehow wide chest is preserving somthing across restarts, maybe it has hidden settings that it changes after launchhing for the first time? No idea really what it's doing.

I guess I'll just try and and Wide Chest and/or Wide Chests all types as an optional dependency that should force it to load after wide chests and fix this at least in theory (unless it's another mod that messes with stack sizes)
